export const countries = [
    {
        name:"United Arab Emirates",
        value:"ae"
    },
    {
        name:"Argentina",
        value:"ar"
    },
    {
        name:"Austria",
        value:"at"
    },
    {
        name:"Belgium",
        value:"be"
    },
    {
        name:"Bulgaria",
        value:"bg"
    },
    {
        name:"Brazil",
        value:"br"
    },
    {
        name:"Canada",
        value:"ca"
    },
    {
        name:"Switzerland",
        value:"ch"
    },
    {
        name:"China",
        value:"cn"
    },
    {
        name:"Colombia",
        value:"co"
    },
    {
        name:"Cuba",
        value:"cu"
    },
    {
        name:"Czechia",
        value:"cz"
    },
    {
        name:"Germany",
        value:"de"
    },
    {
        name:"Egypt",
        value:"eg"
    },
    {
        name:"France",
        value:"fr"
    },
    {
        name:"United Kindom",
        value:"gb"
    },
    {
        name:"Greece",
        value:"gr"
    },
    {
        name:"Hongkong",
        value:"hk"
    },
    {
        name:"Hungary",
        value:"hu"
    },
    {
        name:"Indonesia",
        value:"id"
    },
    {
        name:"Ireland",
        value:"ie"
    },
    {
        name:"Israel",
        value:"il"
    },
    {
        name:"India",
        value:"in"
    },
    {
        name:"Italy",
        value:"it"
    },
    {
        name:"Japan",
        value:"jp"
    },
    {
        name:"Korea",
        value:"kr"
    },
    {
        name:"Liuthvania",
        value:"lt"
    },
    {
        name:"Latvia",
        value:"lv"
    },
    {
        name:"Morocco",
        value:"ma"
    },
    {
        name:"Mexico",
        value:"mx"
    },
    {
        name:"Malaysia",
        value:"my"
    },
    {
        name:"Nigeria",
        value:"ng"
    },
    {
        name:"Netherlands",
        value:"nl"
    },
    {
        name:"Norway",
        value:"no"
    },
    {
        name:"New Zealand",
        value:"nz"
    },
    {
        name:"Philippines",
        value:"ph"
    },
    {
        name:"Poland",
        value:"pl"
    },
    {
        name:"Portugal",
        value:"pt"
    },
    {
        name:"Romania",
        value:"ro"
    },
    {
        name:"Serbia",
        value:"rs"
    },
    {
        name:"Russia",
        value:"ru"
    },
    {
        name:"Saudi Arabia",
        value:"sa"
    },
    {
        name:"Sweden",
        value:"se"
    },
    {
        name:"Singapore",
        value:"sg"
    },
    {
        name:"Slovenia",
        value:"si"
    },
    {
        name:"Slovakia",
        value:"sk"
    },
    {
        name:"Thailand",
        value:"th"
    },
    {
        name:"Turkey",
        value:"tr"
    },
    {
        name:"Taiwan",
        value:"tw"
    },
    {
        name:"Ukraine",
        value:"ua"
    },
    {
        name:"USA",
        value:"us"
    },
    {
        name:"Venezuela",
        value:"ve"
    },
    {
        name:"South Africa",
        value:"za"
    }
]